CREATE TABLE BOARD_COMMENT(
        "BOARD_COMMENT_NO" NUMBER,
        "BOARD_COMMENT_LEVEL" NUMBER DEFAULT 1,
        "BOARD_COMMENT_WRITER" VARCHAR2(15), 
        "BOARD_COMMENT_CONTENT" VARCHAR2(2000), 
        "BOARD_REF" NUMBER, 
        "BOARD_COMMENT_REF" NUMBER, 
        "BOARD_COMMENT_DATE" DATE DEFAULT SYSDATE, 
        CONSTRAINT PK_BOARD_COMMENT_NO PRIMARY KEY(BOARD_COMMENT_NO),
        CONSTRAINT FK_BOARD_COMMENT_WRITER FOREIGN KEY(BOARD_COMMENT_WRITER) REFERENCES MEMBER(USERID) ON DELETE SET NULL,
        CONSTRAINT FK_BOARD_REF FOREIGN KEY(BOARD_REF) REFERENCES BOARD(BOARD_NO) ON DELETE CASCADE,
        CONSTRAINT FK_BOARD_COMMENT_REF FOREIGN KEY(BOARD_COMMENT_REF) REFERENCES BOARD_COMMENT(BOARD_COMMENT_NO) ON DELETE CASCADE
);

--DROP TABLE BOARD_COMMENT;

COMMENT ON COLUMN BOARD_COMMENT.BOARD_COMMENT_NO IS '게시판댓글번호';
COMMENT ON COLUMN BOARD_COMMENT.BOARD_COMMENT_LEVEL IS '게시판댓글 레벨';
COMMENT ON COLUMN BOARD_COMMENT.BOARD_COMMENT_WRITER IS '게시판댓글 작성자';
COMMENT ON COLUMN BOARD_COMMENT.BOARD_COMMENT_CONTENT IS '게시판댓글';
COMMENT ON COLUMN BOARD_COMMENT.BOARD_REF IS '참조원글번호';
COMMENT ON COLUMN BOARD_COMMENT.BOARD_COMMENT_REF IS '게시판댓글 참조번호';
COMMENT ON COLUMN BOARD_COMMENT.BOARD_COMMENT_DATE IS '게시판댓글 작성일';

CREATE SEQUENCE SEQ_BOARD_COMMENT_NO
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;

INSERT INTO BOARD_COMMENT VALUES(SEQ_BOARD_COMMENT_NO.NEXTVAL, DEFAULT, 'opqr','주환님이 저를 괴롭힙니다.',23,NULL,DEFAULT);
INSERT INTO BOARD_COMMENT VALUES(SEQ_BOARD_COMMENT_NO.NEXTVAL, DEFAULT, 'efgh','주환 바보 멍청이~^^',23,NULL,DEFAULT);
SELECT * FROM BOARD_COMMENT;

SELECT * FROM (
	SELECT * FROM BOARD
		JOIN MEMBER ON USERID = BOARD_WRITER
		LEFT JOIN BOARD_COMMENT ON BOARD_NO = BOARD_REF
)WHERE BOARD_NO = 23
START WITH BOARD_COMMENT_LEVEL = 1
CONNECT BY PRIOR BOARD_COMMENT_NO = BOARD_COMMENT_REF;

SELECT * FROM (SELECT * 
				FROM BOARD LEFT JOIN BOARD_COMMENT ON BOARD_NO=BOARD_REF 
				WHERE BOARD_NO=23) 
				START WITH BOARD_COMMENT_LEVEL=1 
				CONNECT BY PRIOR BOARD_COMMENT_NO=BOARD_COMMENT_REF;
			
			SELECT * FROM(SELECT ROWNUM AS RNUM, B.* FROM(SELECT * FROM BOARD LEFT JOIN BOARD_COMMENT ON BOARD_NO=BOARD_REF ORDER BY BOARD_DATE DESC) B )WHERE RNUM BETWEEN ? AND ?;

SELECT * FROM (SELECT ROWNUM AS RNUM, B.* FROM(SELECT * FROM BOARD LEFT JOIN BOARD_COMMENT ON BOARD_NO=BOARD_REF ORDER BY BOARD_DATE DESC)B)WHERE RNUM BETWEEN 1 AND 5;
SELECT * FROM(SELECT ROWNUM AS RNUM, N.* FROM (SELECT * FROM BOARD ORDER BY BOARD_DATE DESC) N );

SELECT * FROM BOARD_COMMENT;
SELECT * FROM BOARD_COMMENT WHERE BOARD_COMMENT_LEVEL = 1 AND BOARD_REF=23;
--대댓글
--INSERT INTO BOARD_COMMENT VALUES(SEQ_BOARD_COMMENT_NO.NEXTVAL, 2, 'stuv','좋은 정보가 어디에...?',21,30,DEFAULT);
--INSERT INTO BOARD_COMMENT VALUES(SEQ_BOARD_COMMENT_NO.NEXTVAL, 2, 'efgh','맞아요^^',21,30,DEFAULT);
--INSERT INTO BOARD_COMMENT VALUES(SEQ_BOARD_COMMENT_NO.NEXTVAL, 2, 'wxyz','얼씨구..',21,28,DEFAULT);
--INSERT INTO BOARD_COMMENT VALUES(SEQ_BOARD_COMMENT_NO.NEXTVAL, 2, 'wxyz','저는 보입니다.',21,30,DEFAULT);
--INSERT INTO BOARD_COMMENT VALUES(SEQ_BOARD_COMMENT_NO.NEXTVAL, 2, 'hijk','뭐임....',21,28,DEFAULT);